/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package akka.typed.app


import akka.actor.typed.scaladsl._
import akka.actor.typed.{ActorSystem, Behavior}


object MainActor {
  def apply(): Behavior[Any] = Behaviors.setup { context =>
    val counter = context.spawn(CounterActor(), "counter")
    context.spawn(ProducerActor(counter), "timed-producer")
    context.spawn(QueryActor(counter), "timed-query")
    Behaviors.same
  }
}

object App {
  def main(args: Array[String]): Unit = {
    ActorSystem(MainActor(), "tick-system")
  }
}